### PR TITLE
Add support for running lightouse via node scripts in package.json

### PR DESCRIPTION
**Pull request by jorntx**
Added support for running lighthouse via node scripts in package.json:

- full test suite `npm run test:full` 
- seperate lighthouse test `npm run test:lh`
 
Added support for customising lighthouse target url via .env.local and **added default conf to configuration system (Aegis)**. Instead of this cumbersome way of modding the target url this should have been done by overriding package.json config values via arguments when calling the script. Unfortunately the support for this has been yanked pr. design --> https://github.com/npm/cli/issues/3475 

Added support for Windows environment variables

### CODE REVIEW

**Comment by jesperlauridsen** [comment]
Can you resolve the conflicts here, @jorntx  :-)

**Comment by jesperlauridsen** [comment]
@jorntx ,
After doing an npm install i got now

9 vulnerabilities (5 moderate, 4 high).

This seems ... new?

Also, trying to run the script gives me:

jesper@jela:~/KBCode/ds-web$ npm run test:lh

> ds-web@0.2.0 test:lh
> dotenv -e .env.local cross-var lighthouse %LIGHTHOUSE_TARGET_URL% -- --view


I assume that's because i'm missing the new variable. Which is in aegis. But I've done a git pull on the master branch, so this should be good to go, no?

**Comment by jorntx** [comment]
Fixed the 4 high vulnerabilities by going with a fork of cross-var (yes I vetted the whole code...)

You are correct about the error when running `npm run test:lh` and you can fix this by getting a fresh .env from Aegis as hinted with bold in the PR description:)

**Comment by jorntx** [comment]
Øjjj, thanks for reporting the issue on your machine. Turns out the reason the lighthouse script won't run on your machine is a big bobooo on my part. Forgot to include the lighthouse package - dohhhh! The reason it worked for me was that I had it as a global dep.

All fixed now. 
Pull --> npm install --> start the dev server --> fix the target url param (if necessary) --> npm run test:lh

**Comment by jesperlauridsen** [comment]
It works now! Very nice! I got a

**Comment by jorntx** [comment]
Yes, lets make a note and see if we can tune the default "statistics" behaviour in a future PR

**Comment by jorntx** [comment]
Saw the comment - made a seperate issue - we are good to go here!

**Pull request merged**
